//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POScreen.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_FetchSO
    {
        public string SalesOrder { get; set; }
        public string OrderDate { get; set; }
        public string ReqShipDate { get; set; }
        public Nullable<System.DateTime> RDate { get; set; }
        public string Salesperson { get; set; }
        public string Customer { get; set; }
        public string CustomerName { get; set; }
        public string OrderStatus { get; set; }
    }
}
